// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiDQI4b7ZMP0ZkkKKHsWDjZJM6GO49LeA',
    appId: '1:193803355257:web:35530c3c4beacea7b440a8',
    messagingSenderId: '193803355257',
    projectId: 'olx-apps-1e931',
    authDomain: 'olx-apps-1e931.firebaseapp.com',
    storageBucket: 'olx-apps-1e931.appspot.com',
    measurementId: 'G-0TSFCG0KK3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6G8VkV1FhbLgQhgkFogkWgdyTZeW1uVs',
    appId: '1:193803355257:android:6c3b9f12355ea23bb440a8',
    messagingSenderId: '193803355257',
    projectId: 'olx-apps-1e931',
    storageBucket: 'olx-apps-1e931.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjKpTcDM7udiK_IG9-d20P8zS6AL07MK4',
    appId: '1:193803355257:ios:3e30be6989753a66b440a8',
    messagingSenderId: '193803355257',
    projectId: 'olx-apps-1e931',
    storageBucket: 'olx-apps-1e931.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjKpTcDM7udiK_IG9-d20P8zS6AL07MK4',
    appId: '1:193803355257:ios:d71a636ef25770b1b440a8',
    messagingSenderId: '193803355257',
    projectId: 'olx-apps-1e931',
    storageBucket: 'olx-apps-1e931.appspot.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
